import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "about page",
  description: "Generated by about page",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>this is only for about page</nav>
        {children}
      </body>
    </html>
  );
}
