import { Example } from "../components/NavDesktopToggle/Popup";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-light">
          <div className="absoluten right-0 z-50">
            <Example />
          </div>
          <Navbar />
        </nav>
        {children}
      </body>
    </html>
  );
}
